# Copyright 2022 Florian Eich <florian.eich@gmail.com>
#
# This work is licensed under the Apache License, Version 2.0. You should have
# received a copy of this license along with the source code. If that is not
# the case, please find one at http://www.apache.org/licenses/LICENSE-2.0.

[broker]
broadcast_capacity = 256


[database]
host = "localhost"
user = "postgres"
password = "barbershop"
dbname = "doi105281zenodo1167595"


[[sinks]]
subscribes_to = ["moving"]

[[sinks]]
subscribes_to = ["highSpeed"]


[source]
publishes = ["lon", "lat", "speed"]

  [source.run_params]
  millis_per_cycle = 100
  datapoints_to_run = 100000

  [source.query_params]
  key_name = "mmsi"
  timestamp_name = "ts"
  from_table = "ais_data.dynamic_ships"
  order_by = "id"
  rows_to_fetch = 32
