# Copyright 2022 Florian Eich <florian.eich@gmail.com>
#
# This work is licensed under the Apache License, Version 2.0. You should have
# received a copy of this license along with the source code. If that is not
# the case, please find one at http://www.apache.org/licenses/LICENSE-2.0.

buffer_timeout = 3600


[broker]
broadcast_capacity = 256


[database]
host = "localhost"
user = "postgres"
password = "barbershop"
dbname = "doi105281zenodo1167595"

# [[sinks]]
# debug = true
# write_timeout = 80
# subscribes_to = ["lon", "lat", "location"]

[[sinks]]
debug = true
write_timeout = 80
subscribes_to = [
  "high_speed",
  "near_coast",
  "high_speed_near_coast"
]

[[sinks]]
debug = true
write_timeout = 80
subscribes_to = [
  "proximity",
  "distance"
]

[[sinks]]
debug = true
write_timeout = 80
subscribes_to = [
  "stopped_or_low_speed",
  "near_coast",
  "near_ports",
  "is_tug_or_pilot"
]

[[sinks]]
debug = true
write_timeout = 80
subscribes_to = [
  "rendez_vous",
  "rendez_vous_candidates",
  "rendez_vous_conditions"
]


[source]
publishes = ["lon", "lat", "speed"]

  [source.run_params]
  millis_per_cycle = 100
  datapoints_to_run = 100000

  [source.query_params]
  key_name = "mmsi"
  timestamp_name = "ts"
  from_table = "ais_data.dynamic_ships"
  order_by = "id"
  rows_to_fetch = 32
